project:
  type: website
  output-dir: docs

website:
  title: "Metagen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: labs.qmd
        text: Labs
      - href: projects.qmd
        text: Projects
      - href: survey.qmd
        text: Survey
format:
  html:
    toc: true
    toc_float: true
    code-fold: true
    code-summary: "R code"
    embed-resources: true
    theme: yeti
    css: styles.css

editor: source

execute:
  warning: false
  message: false