project:
  type: website
  output-dir: docs

website:
  title: "PathoGen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: labs.qmd
        text: Labs
      - href: schedule.qmd
        text: Schedule        
      - href: projects.qmd
        text: Projects
format:
  html:
    toc: true
    toc_float: true
    code-fold: show
    code-summary: "R code"
    embed-resources: true
    theme: yeti
    css: styles.css

editor: source

execute:
  warning: false
  message: false